[project]
name = "mcp-local-rag"
version = "0.1.0"
description = "MCP \"server\" that locally performs a RAG search on your input query."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
 "mcp[cli]>=1.6.0",
 "mediapipe",
 "beautifulsoup4",
 "duckduckgo-search",
 "httpx",
]
[[project.authors]]
name = "Nikhil Kapila"
email = "info@nkapila.me"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-local-rag = "mcp_local_rag.main:mcp.run"

[tool.setuptools.package-data]
mcp_local_rag = ["embedder/embedder.tflite"]

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_local_rag"]